name: main branch workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  main_branch_workflow:
    name: main branch workflow
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: read .node-version, project version & set NODE_VERSION, PROJECT_VERSION environment variables
        run: |
          NODE_VERSION=$(cat .node-version | head -n 1 | tr -d '\n')
          PROJECT_VERSION=$(jq -r .version package.json)
          echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_ENV
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV
          echo "NODE_VERSION=$NODE_VERSION, PROJECT_VERSION=$PROJECT_VERSION"

      - name: setup node.js $NODE_VERSION
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.node-version'

      - name: install dependencies
        run: npm ci

      - name: run tests
        run: npm test

      - name: build project
        run: npm run build

      - name: github container registry login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            NODE_VERSION=${{ env.NODE_VERSION }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.PROJECT_VERSION }}
